#!/usr/bin/env bash

# Push all changed made to the notes to the Git remote.
# If an argument is passed to this script, it's used as
# the commit message for the update.

set -e

if [ ! -x "$(command -v git)" ]; then
    >&2 echo "$0: git is not installed"
    exit 1
fi

commitmsg="$1"
if [ -z "$commitmsg" ]; then
    commitmsg="Update notes"
fi

set -x

git add .
git commit -m "$commitmsg"
git push
